name: mvvm
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.0-214.0.dev <3.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  http: ^1.2.1
  fluttertoast: ^8.0.9
  another_flushbar: ^1.12.29
  get_storage: ^2.0.3
  shared_preferences: ^2.0.15
  go_router: ^14.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  riverpod_generator: ^2.2.6
  build_runner: ^2.4.6


flutter:


  uses-material-design: true

